name: Update IPO JSON

on:
  schedule:
    # Jam 12:30 UTC = 19:30 WIB
    - cron: "30 12 * * *"
  workflow_dispatch: # Bisa juga dijalankan manual dari tab Actions

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas kaggle

      - name: Download data from Kaggle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p data
          kaggle datasets download -d fahmirk/underwriters-track-record-e-ipo -p data --unzip
          ls -lh data

      - name: Convert CSV to JSON
        run: |
          python scripts/convert_to_json.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ipo.json
          git commit -m "Auto update JSON from Kaggle" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
